### ISSUE TITLE
Not working with Rails 5.2

### ISSUE THREAD

**Issue by Codcore** [jonhue/acts_as_favoritor#168]
It does not works with Rails 5.2 as it use `ApplicationRecord` as base class for models instead of `ActiveRecord::Base`. So I get `undefined method 'relation_delegate_class'` error when use it with my models. But it works good with models derived from ActiveRecord::Base. I really do not know how to fix that

**Comment by djaircarvalho** [comment]
Hi @Codcore what version of the gem are you using?

**Comment by jonhue** [comment]
Closed due to inactivity
